pub_cache:
  folder: ~/.pub-cache

task:
  container:
    dockerfile: .ci/Dockerfile
  upgrade_script:
    - flutter channel stable
    - flutter upgrade
    - flutter channel master
    - flutter upgrade
    - git fetch origin master
    - pub global activate melos
  allow_failures: $CHANNEL == "master"
  matrix:
    - name: analyze
      env:
        matrix:
          CHANNEL: "master"
          CHANNEL: "stable"
      test_script: 
        - export PATH="$PATH":"$HOME/.pub-cache/bin"
        - flutter channel $CHANNEL
        - melos bootstrap
        - melos run lint:all
    - name: test
      env:
        CODECOV_TOKEN: ENCRYPTED[ac3e49abb66606b10e1bacc05c45c5f6325e3677770fba1c935a71a8854ec73017b61492ab167a7bedd96a4cc9e1e644]
        matrix:
          CHANNEL: "master"
          CHANNEL: "stable"
      test_script:
        - export PATH="$PATH":"$HOME/.pub-cache/bin"
        - flutter channel $CHANNEL
        - melos bootstrap
        - melos run test --no-select
        - cd packages/location
        - if [ $CHANNEL = "stable" ]; then bash <(curl -s https://codecov.io/bash); fi
        - cd ../location_platform_interface
        - if [ $CHANNEL = "stable" ]; then bash <(curl -s https://codecov.io/bash); fi


